default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>

development:
  <<: *default
  database: animalbox_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: animalbox_test
  host: db
  username: root
  password: password

production:
  <<: *default
  database: animalbox_production
  username: animalbox
  password: <%= ENV['ANIMALBOX_DATABASE_PASSWORD'] %>
