
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  socket: /tmp/mysql.sock
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>


development:
  <<: *default
  database: img_development

test:
  <<: *default
  database: img_test

production:
  <<: *default
  database: animalbox_production
  username: root
  password: password
  host: host